### PR TITLE
mxf2raw: extend `--rdd6` option description

### PR DESCRIPTION
**Pull request by philipnbbc**
Fixes https://github.com/bbc/bmx/issues/44

### CODE REVIEW

**Comment by thomasheritage** [comment]
Thanks, it's very useful to have this documented more thoroughly.

A few thoughts:
* There's no indication given if the `frames` value was insufficient to allow complete program descriptions to be extracted for all programs
* If there were multiple programs in the bitstream can they in practice be included in the XML? It looks like the XML only supports a single program description.
  * I don't think we have a use case for multiple programs -- if mxf2raw can't fully support this then this could be noted in the help text
* Presumably mxf2raw _assumes_ that the RDD 6 metadata is static except for _both_  `frame_count` and `description_text` i.e. there are two non-static fields
  * Presumably mxf2raw only reads RDD 6 metadata (except for those two fields) from the first frame indicated in the `frames` commandline parameter? i.e. won't notice if other values actually vary
* Perhaps remove the "Set the <frames> ..." paragraph from https://github.com/bbc/bmx/tree/main/meta/rdd6_xml_creator to avoid conflicting text / having to maintain the text in two places

**Comment by philipnbbc** [comment]
I've updated the PR to
* improve the option description following your comments,
* log a warning if the description text is not complete for all programs,
* remove the redundant text in the rdd6_xml_creator app

The RDD 6 XML schema [defines](https://github.com/bbc/bmx/blob/main/meta/rdd6/rdd6.xsd#L100) the `desc_text` element to have at most 8 `program`s. See table 6.2 of the [RDD 6 spec.](https://ieeexplore.ieee.org/document/7290141). E.g. if there is 5.1 and stereo audio then that is represented as 2 RDD 6 programs.

**Comment by philipnbbc** [comment]
> Just one outstanding item:
> 
> > presumably mxf2raw only reads RDD 6 metadata (except for those two fields) from the first frame indicated in the frames commandline parameter? i.e. won't notice if other values actually vary

Yes, it assumes it is static and doesn't check if it isn't.

> 
> On this topic, the help text says:
> 
> > The output XML will contain the static RDD 6 metadata
> 
> Perhaps you can just add something to convey whether this RDD 6 metadata being _static_ is just an assumption, or whether mxf2raw actually checks that it's static (for the frames that it reads)?

I've changed it to say it assumes it is static and that it uses the non-first frames to accumulate the description text.

**Comment by thomasheritage** [comment]
LGTM

**Review by thomasheritage — APPROVED** [review]

**Pull request merged**
